library(tidyverse)
library(batchelor)
library(Seurat)
library(Matrix)
library(fossil, include.only = 'rand.index')
library(pdfCluster, include.only = 'adj.rand.index')
library(hdf5r)
library(SeuratWrappers)
library(gprofiler2)
library(future)
library(SeuratDisk)

unloadNamespace("Rcpp")

#Sessioninfo
sessionInfo()
## We can use multiple cores for some functions, see: https://satijalab.org/seurat/v3.2/future_vignette.html
plan("multisession", workers = 2)
plan("sequential")
plan()

clust_char <- function(seuratobj, metavariable="seurat_clusters"){
  outputdf <- seuratobj[[metavariable]] %>% rownames_to_column()
  factor_columns <- sapply(outputdf, is.factor)
  outputdf[factor_columns] <- lapply(outputdf[factor_columns], as.character)
  outputdf <- outputdf %>% column_to_rownames()
  return(outputdf)
}

kal_merged[["seurat_clusters_ch"]] <- clust_char(kal_merged)
SaveH5Seurat(kal_merged, filename = "/exports/sascstudent/thomas/R_output/kal_merged.h5seurat", overwrite = T)
Convert("/exports/sascstudent/thomas/R_output/kal_merged.h5seurat", dest = "h5ad", overwrite = T)

kal_inhouse <- readRDS("/exports/sascstudent/thomas/R_output/hiPSC_kallisto_inhouse_mnn.rds")
kal_inhouse[["seurat_clusters_ch"]] <- clust_char(kal_inhouse)
SaveH5Seurat(kal_inhouse, filename = "/exports/sascstudent/thomas/R_output/kal_inhouse.h5seurat", overwrite = T)
Convert("/exports/sascstudent/thomas/R_output/kal_inhouse.h5seurat", dest = "h5ad", overwrite = T)

cell_merged[["seurat_cluster_ch"]] <- clust_char(cell_merged)
SaveH5Seurat(cell_merged, filename = "/exports/sascstudent/thomas/R_output/cell_merged.h5seurat", overwrite = T)
Convert("/exports/sascstudent/thomas/R_output/cell_merged.h5seurat", dest = "h5ad", overwrite = T)


remove(H0_sample1, H0_sample2, H48_sample, H120_sample)
remove(kal_inhouse, kal_pbmc.genes, kal_pbmc.markers)

CELLRANGERFOL="/exports/sascstudent/thomas/output/cellranger/"
KALBUSFOL="/exports/sascstudent/thomas/output/bustools/"

# Slightly modified from BUSpaRse, just to avoid installing a few dependencies not used here
read_count_output <- function(dir, name) {
  dir <- normalizePath(dir, mustWork = TRUE)
  m <- readMM(paste0(dir, "/", name, ".mtx"))
  m <- Matrix::t(m)
  m <- as(m, "dgCMatrix")
  # The matrix read has cells in rows
  ge <- ".genes.txt"
  genes <- readLines(file(paste0(dir, "/", name, ge)))
  barcodes <- readLines(file(paste0(dir, "/", name, ".barcodes.txt")))
  colnames(m) <- barcodes
  rownames(m) <- genes
  return(m)
}

load_kalbus <- function(kbfolder, projectname) {
  res_mat <- read_count_output(paste0(kbfolder, "/counts_unfiltered"), name = "cells_x_genes")
  # Convert from Ensembl gene ID to gene symbol
  rownames(res_mat) <- tr2g$gene_symbol[match(rownames(res_mat), tr2g$gene)]
  kal_pbmc <- CreateSeuratObject(counts = res_mat, project = projectname, min.cells = 3, min.features = 100)
  remove(res_mat)
  return(kal_pbmc)
}


tr2g <- read_tsv(paste0("/exports/sascstudent/thomas/ref_indices/GRch38_kallisto_cdna", "/tr2g.txt"), progress = F,
                 col_names = c("transcript", "gene", "gene_symbol","gene_full_symbol","chr","start","end","strand")) %>% select(-c(transcript, gene_full_symbol, chr, start, end, strand)) %>% distinct()


#Data loading and annotation
{
  #Loading of data generated by Kallisto Bustools
  H0_sample1 <- load_kalbus(paste0(KALBUSFOL, "1_mesonephros_0H"), projectname = "sample1_0H")
  H0_sample2 <- load_kalbus(paste0(KALBUSFOL, "2_mesonephros_0H"), projectname = "sample2_0H")
  H48_sample <- load_kalbus(paste0(KALBUSFOL, "sample_48H"), projectname = "sample_48H")
  H120_sample <- load_kalbus(paste0(KALBUSFOL, "sample_120H"), projectname = "sample_120H")
  
  kal_inhouse_before <- merge(H120_sample, y = c(H0_sample1, H0_sample2, H48_sample), add.cell.ids = c("batch_1_sample_120H", "batch_2_A", "batch_2_B", "batch_1_sample_48H"), project = "mesonephros")
  remove(H0_sample1, H0_sample2, H48_sample, H120_sample)
  gc()
  sample_mapping <- read_tsv("/exports/sascstudent/thomas/hiPSC_susana/sample_name_full_dataset.tsv", 
                             skip = 1, col_names = c("rownames","sample_name")) %>% column_to_rownames(., var = "rownames")
  rownames(sample_mapping) <- rownames(sample_mapping) %>% str_sub(end = -3)
  kal_inhouse_before[["sample_name"]] <- sample_mapping
}


{
  PGCLCd1_b1 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd1-batch1"), projectname = "D1_rep1")
  PGCLCd2_b1 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd2-batch1"), projectname = "D2_rep1")
  PGCLCd3_b1 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd3-batch1"), projectname = "D3_rep1")
  PGCLCd4_b1 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd4-batch1"), projectname = "D4_rep1")
  hESC_b1 <- load_kalbus(paste0(KALBUSFOL, "hESC-batch1"), projectname = "hESC_rep1")
  iMeLC_b1 <- load_kalbus(paste0(KALBUSFOL, "iMeLC-batch1"), projectname = "iMeLC_rep1")
  
  PGCLCd1_b2 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd1-batch2"), projectname = "D1_rep2")
  PGCLCd2_b2 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd2-batch2"), projectname = "D2_rep2")
  PGCLCd3_b2 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd3-batch2"), projectname = "D3_rep2")
  PGCLCd4_b2 <- load_kalbus(paste0(KALBUSFOL, "PGCLCd4-batch2"), projectname = "D4_rep2")
  hESC_b2 <- load_kalbus(paste0(KALBUSFOL, "hESC-batch2"), projectname = "hESC_rep2")
  iMeLC_b2 <- load_kalbus(paste0(KALBUSFOL, "iMeLC-batch2"), projectname = "iMeLC_rep2")
  
  gc()
}

{
  #Replicate 1
  PGCLCd1_b1[["sample_id"]] <- "D1_rep1"
  PGCLCd1_b1[["replicate"]] <- "rep1"
  PGCLCd1_b1[["timepoint"]] <- "D1"
  
  PGCLCd2_b1[["sample_id"]] <- "D2_rep1"
  PGCLCd2_b1[["replicate"]] <- "rep1"
  PGCLCd2_b1[["timepoint"]] <- "D2"
  
  PGCLCd3_b1[["sample_id"]] <- "D3_rep1"
  PGCLCd3_b1[["replicate"]] <- "rep1"
  PGCLCd3_b1[["timepoint"]] <- "D3"
  
  PGCLCd4_b1[["sample_id"]] <- "D4_rep1"
  PGCLCd4_b1[["replicate"]] <- "rep1"
  PGCLCd4_b1[["timepoint"]] <- "D4"
  
  hESC_b1[["sample_id"]] <- "hESC_rep1"
  hESC_b1[["replicate"]] <- "rep1"
  hESC_b1[["timepoint"]] <- "hESC"
  
  iMeLC_b1[["sample_id"]] <- "iMeLC_rep1"
  iMeLC_b1[["replicate"]] <- "rep1"
  iMeLC_b1[["timepoint"]] <- "iMeLC"
  
  #Replicate 2
  
  PGCLCd1_b2[["sample_id"]] <- "D1_rep2"
  PGCLCd1_b2[["replicate"]] <- "rep2"
  PGCLCd1_b2[["timepoint"]] <- "D1"
  
  PGCLCd2_b2[["sample_id"]] <- "D2_rep2"
  PGCLCd2_b2[["replicate"]] <- "rep2"
  PGCLCd2_b2[["timepoint"]] <- "D2"
  
  PGCLCd3_b2[["sample_id"]] <- "D3_rep2"
  PGCLCd3_b2[["replicate"]] <- "rep2"
  PGCLCd3_b2[["timepoint"]] <- "D3"
  
  PGCLCd4_b2[["sample_id"]] <- "D4_rep2"
  PGCLCd4_b2[["replicate"]] <- "rep2"
  PGCLCd4_b2[["timepoint"]] <- "D4"
  
  hESC_b2[["sample_id"]] <- "hESC_rep2"
  hESC_b2[["replicate"]] <- "rep2"
  hESC_b2[["timepoint"]] <- "hESC"
  
  iMeLC_b2[["sample_id"]] <- "iMeLC_rep2"
  iMeLC_b2[["replicate"]] <- "rep2"
  iMeLC_b2[["timepoint"]] <- "iMeLC"
}

#kal_inhouse <- readRDS("/exports/sascstudent/thomas/R_output/hiPSC_kallisto_inhouse_mnn.rds")
Idents(kal_inhouse) <- "hiPSC"
kal_inhouse[["sample_id"]] <- "hiPSC"
kal_inhouse[["replicate"]] <- "hiPSC"
kal_inhouse[["timepoint"]] <- "hiPSC"
kal_inhouse[["hiPSC_only_clustering"]] <- kal_inhouse[["seurat_clusters"]]


kal_merged <- merge(x = PGCLCd1_b1, y = c(PGCLCd2_b1, PGCLCd3_b1,PGCLCd4_b1,hESC_b1,iMeLC_b1,
                                          PGCLCd1_b2,PGCLCd2_b2,PGCLCd3_b2,PGCLCd4_b2,hESC_b2,
                                          iMeLC_b2, kal_inhouse), 
                    add.cell.ids = c("UCLA2_iMeLC_day1_hPGCLC_day1_rep1","UCLA2_iMeLC_day1_hPGCLC_day2_rep1",
                                     "UCLA2_iMeLC_day1_hPGCLC_day3_rep1","UCLA2_iMeLC_day1_hPGCLC_day4_rep1",
                                     "UCLA2_hESC_rep1","UCLA2_iMeLC_day1_rep1","UCLA2_iMeLC_day1_hPGCLC_day1_rep2",
                                     "UCLA2_iMeLC_day1_hPGCLC_day2_rep2","UCLA2_iMeLC_day1_hPGCLC_day3_rep2",
                                     "UCLA2_iMeLC_day1_hPGCLC_day4_rep2","UCLA2_hESC_rep2","UCLA2_iMeLC_day1_rep2",
                                     "hiPSC"))

remove(PGCLCd1_b1,PGCLCd2_b1,PGCLCd3_b1,PGCLCd4_b1,hESC_b1,iMeLC_b1,PGCLCd1_b2,PGCLCd2_b2,PGCLCd3_b2,PGCLCd4_b2,hESC_b2,iMeLC_b2)
remove(kal_inhouse)
gc()

#Gene dissociation
genesChrom <- c("Actg1__chr11","Ankrd1__chr19","Arid5a__chr1","Atf3__chr1","Atf4__chr15","Bag3__chr7","Bhlhe40__chr6",
                "Brd2__chr17","Btg1__chr10","Btg2__chr1","Ccnl1__chr3","Ccrn4l__chr3","Cebpb__chr2","Cebpd__chr16",
                "Cebpg__chr7","Csrnp1__chr9","Cxcl1__chr5","Cyr61__chr3","Dcn__chr10","Ddx3x__chrX","Ddx5__chr11",
                "Des__chr1","Dnaja1__chr4","Dnajb1__chr8","Dnajb4__chr3","Dusp1__chr17","Dusp8__chr7",
                "Egr1__chr18","Egr2__chr10","Eif1__chr11","Eif5__chr12","Erf__chr7","Errfi1__chr4","Fam132b__chr1",
                "Fos__chr12","Fosb__chr7","Fosl2__chr5","Gadd45a__chr6","Gcc1__chr6","Gem__chr4","H3f3b__chr11",
                "Hipk3__chr2","Hsp90aa1__chr12","Hsp90ab1__chr17","Hspa1a__chr17","Hspa1b__chr17","Hspa5__chr2",
                "Hspa8__chr9","Hspb1__chr5","Hsph1__chr5","Id3__chr4","Idi1__chr13","Ier2__chr8","Ier3__chr17",
                "Ifrd1__chr12","Il6__chr5","Irf1__chr11","Irf8__chr8","Itpkc__chr7","Jun__chr4","Junb__chr8",
                "Jund__chr8","Klf2__chr8","Klf4__chr4","Klf6__chr13","Klf9__chr19","Litaf__chr16","Lmna__chr3",
                "Maff__chr15","Mafk__chr5","Mcl1__chr3","Midn__chr10","Mir22hg__chr11","Mt1__chr8","Mt2__chr8",
                "Myadm__chr7","Myc__chr15","Myd88__chr9","Nckap5l__chr15","Ncoa7__chr10","Nfkbia__chr12","Nfkbiz__chr16",
                "Nop58__chr1","Nppc__chr1","Nr4a1__chr15","Odc1__chr12","Osgin1__chr8","Oxnad1__chr14","Pcf11__chr7",
                "Pde4b__chr4","Per1__chr11","Phlda1__chr10","Pnp__chr14","Pnrc1__chr4","Ppp1cc__chr5","Ppp1r15a__chr7",
                "Pxdc1__chr13","Rap1b__chr10","Rassf1__chr9","Rhob__chr12","Rhoh__chr5","Ripk1__chr13","Sat1__chrX",
                "Sbno2__chr10","Sdc4__chr2","Serpine1__chr5","Skil__chr3","Slc10a6__chr5","Slc38a2__chr15",
                "Slc41a1__chr1","Socs3__chr11","Sqstm1__chr11","Srf__chr17","Srsf5__chr12","Srsf7__chr17",
                "Stat3__chr11","Tagln2__chr1","Tiparp__chr3","Tnfaip3__chr10","Tnfaip6__chr2","Tpm3__chr3",
                "Tppp3__chr8","Tra2a__chr6","Tra2b__chr16","Trib1__chr15","Tubb4b__chr2","Tubb6__chr18",
                "Ubc__chr5","Usp2__chr9","Wac__chr18","Zc3h12a__chr4","Zfand5__chr19","Zfp36__chr7","Zfp36l1__chr12",
                "Zfp36l2__chr17","Zyx__chr6","Gadd45g__chr13","Hspe1__chr1","Ier5__chr1","Kcne4__chr1")

genes <- sapply(genesChrom, function(x){
  toupper( strsplit(x, "__")[[1]][1])
})

## Remove mouse only genes and put the corresponding human
genes <- genes[!genes %in% c("CCRN4L", "MT1", "MT2")]
genes <- c(genes, "NOCT", "MT1A", "MT2A")


#Parameters

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

kal_inhouse

{
  #Kallisto inhouse complete process and analysis
  kal_inhouse
  kal_inhouse[["percent.mt"]] <- PercentageFeatureSet(kal_inhouse, pattern = "^MT-")
  kal_inhouse <- subset(kal_inhouse, subset = nFeature_RNA > 2000 & nFeature_RNA < 7000 & percent.mt < 10 & percent.mt > 0.1 & nCount_RNA < 100000)
  gc(verbose = F)
  kal_inhouse <- NormalizeData(kal_inhouse, normalization.method = "LogNormalize", scale.factor = 100000)
  
  #Dissociation genes
  cat("Genes from mouse we miss in human:\n")
  unname(genes[!genes %in% rownames(kal_inhouse)])
  ## Calculate the percentage of UMIs maping on dissociation genes
  totalSum <- Matrix::colSums(GetAssayData(object = kal_inhouse))
  selection <- as.data.frame(as.matrix(GetAssayData(object = kal_inhouse[genes,])))
  # selection <- Data[genes, ]
  selection[is.na(selection)] <- 0
  dissociationSums <- colSums(selection)
  countSums <- merge(totalSum, dissociationSums, by="row.names", all=TRUE, sort= FALSE)
  rownames(countSums) <- countSums$Row.names
  countSums <- countSums[-1]
  colnames(countSums) <- c("totalCount", "dissociationCounts")
  countSums$percentage <- countSums$dissociationCounts/countSums$totalCount
  ## Save in meta.data of object
  kal_inhouse[["percent.dissoc"]] <- countSums$percentage
  ## Draw histogram for all samples
  percentages <- kal_inhouse$percent.dissoc
  hist(percentages,
       breaks = 100,
       col = "lightgrey",
       main = paste("Expression dissociation-affected genes"),
       xlab = "Ratio of dissociation-affected genes to total gene count", ylab = "Number of cells", xlim = c(0, 0.20))
  kal_inhouse <- subset(x = kal_inhouse, subset = percent.dissoc < 0.06)
  dim(kal_inhouse)
  table(kal_inhouse$orig.ident)
  
  remove(dissociationSums, totalSum, selection, countSums, percentages)
  #
  kal_inhouse <- FindVariableFeatures(kal_inhouse)
  kal_inhouse <- ScaleData(kal_inhouse, features = rownames(kal_inhouse))
  gc(verbose = F)
  kal_inhouse <- CellCycleScoring(kal_inhouse, s.features = s.genes, g2m.features = g2m.genes, set.indent=TRUE)
  kal_inhouse <- RunPCA(kal_inhouse, features = VariableFeatures(object = kal_inhouse))
  
  kal_inhouse <- RunFastMNN(object.list = SplitObject(kal_inhouse, split.by = "sample_name"))
  kal_inhouse <- FindNeighbors(kal_inhouse, dims = c(1:15), reduction = "mnn")
  kal_inhouse <- FindClusters(kal_inhouse, resolution = 0.2)
  kal_inhouse <- RunUMAP(kal_inhouse, reduction = "mnn", dims = c(1:15))
  DimPlot(kal_inhouse, reduction = "umap", group.by = "seurat_clusters")
  DimPlot(kal_inhouse, reduction = "umap", group.by = "sample_name")
}

saveRDS(object = kal_inhouse, file = "/exports/sascstudent/thomas/R_output/hiPSC_kallisto_inhouse_mnn.rds")
#kal_inhouse[["seurat_clusters_ch"]] <- clust_char(kal_inhouse)
#SaveH5Seurat(kal_inhouse, filename = "/exports/sascstudent/thomas/R_output/kal_inhouse_testing.h5seurat", overwrite = T)
#Convert("/exports/sascstudent/thomas/R_output/kal_inhouse_testing.h5seurat", dest = "h5ad", overwrite = T)


{
  #Kallisto merged complete process and analysis
  kal_merged
  kal_merged[["percent.mt"]] <- PercentageFeatureSet(kal_merged, pattern = "^MT-")
  kal_merged <- subset(kal_merged, subset = nFeature_RNA > 2000 & nFeature_RNA < 7000 & percent.mt < 10 & percent.mt > 0.1 & nCount_RNA < 100000)
  gc(verbose = F)
  kal_merged <- NormalizeData(kal_merged, normalization.method = "LogNormalize", scale.factor = 100000)
  
  #Dissociation genes
  cat("Genes from mouse we miss in human:\n")
  unname(genes[!genes %in% rownames(kal_merged)])
  ## Calculate the percentage of UMIs maping on dissociation genes
  totalSum <- Matrix::colSums(GetAssayData(object = kal_merged))
  selection <- as.data.frame(as.matrix(GetAssayData(object = kal_merged[genes,])))
  # selection <- Data[genes, ]
  selection[is.na(selection)] <- 0
  dissociationSums <- colSums(selection)
  countSums <- merge(totalSum, dissociationSums, by="row.names", all=TRUE, sort= FALSE)
  rownames(countSums) <- countSums$Row.names
  countSums <- countSums[-1]
  colnames(countSums) <- c("totalCount", "dissociationCounts")
  countSums$percentage <- countSums$dissociationCounts/countSums$totalCount
  ## Save in meta.data of object
  kal_merged[["percent.dissoc"]] <- countSums$percentage
  ## Draw histogram for all samples
  percentages <- kal_merged$percent.dissoc
  hist(percentages,
       breaks = 100,
       col = "lightgrey",
       main = paste("Expression dissociation-affected genes"),
       xlab = "Ratio of dissociation-affected genes to total gene count", ylab = "Number of cells", xlim = c(0, 0.20))
  
  remove(dissociationSums, totalSum, selection, countSums, percentages)
  
  kal_merged <- FindVariableFeatures(kal_merged)
  kal_merged <- ScaleData(kal_merged, features = rownames(kal_merged))
  gc(verbose = F)
  kal_merged <- CellCycleScoring(kal_merged, s.features = s.genes, g2m.features = g2m.genes, set.indent=TRUE)
  kal_merged <- RunPCA(kal_merged, features = VariableFeatures(object = kal_merged))
  
  kal_merged <- RunFastMNN(object.list = SplitObject(kal_merged, split.by = "sample_name"))
  kal_merged <- FindNeighbors(kal_merged, dims = c(1:15), reduction = "mnn")
  kal_merged <- FindClusters(kal_merged, resolution = 0.27)
  kal_merged <- RunUMAP(kal_merged, reduction = "mnn", dims = c(1:15))
}





#Seurat Analysis
# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
cell_pbmc[["percent.mt"]] <- PercentageFeatureSet(cell_pbmc, pattern = "^MT-")
kal_public[["percent.mt"]] <- PercentageFeatureSet(kal_public, pattern = "^MT-")
kal_merged[["percent.mt"]] <- PercentageFeatureSet(kal_merged, pattern = "^MT-")

is.na(kal_inhouse$percent.mt)
is.na(kal_public$percent.mt)

# Visualize QC metrics as a violin plot
VlnPlot(cell_pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),ncol=3)
VlnPlot(kal_inhouse, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),ncol=3)
VlnPlot(kal_public, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),ncol=3)

# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.
plot1 <- FeatureScatter(cell_pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + guides(colour = "none") + ggtitle("cellranger")
plot2 <- FeatureScatter(cell_pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt") + guides(colour = "none") + ggtitle("cellranger")
plot1 + plot2

plot1 <- FeatureScatter(kal_inhouse, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + guides(colour = "none") + ggtitle("KalBus")
plot2 <- FeatureScatter(kal_inhouse, feature1 = "nCount_RNA", feature2 = "percent.mt") + guides(colour = "none") + ggtitle("KalBus")
plot1 + plot2

plot1 <- FeatureScatter(kal_public, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + guides(colour = "none") + ggtitle("KalBus")
plot2 <- FeatureScatter(kal_public, feature1 = "nCount_RNA", feature2 = "percent.mt") + guides(colour = "none") + ggtitle("KalBus")
plot1 + plot2

remove(plot1, plot2)

#Filtering
cell_pbmc <- subset(cell_pbmc, subset = nFeature_RNA > 2000 & nFeature_RNA < 7000 & percent.mt < 10 & percent.mt > 0.1 & nCount_RNA < 100000)
kal_public <- subset(kal_public, subset = nFeature_RNA > 2000 & nFeature_RNA < 7000 & percent.mt < 10 & percent.mt > 0.1 & nCount_RNA < 100000)
kal_merged <- subset(kal_merged, subset = nFeature_RNA > 2000 & nFeature_RNA < 7000 & percent.mt < 10 & percent.mt > 0.1 & nCount_RNA < 100000)
gc()

kal_inhouse
kal_public

#Normalize data
cell_pbmc <- NormalizeData(cell_pbmc, normalization.method = "LogNormalize", scale.factor = 100000)
kal_inhouse <- NormalizeData(kal_inhouse, normalization.method = "LogNormalize", scale.factor = 100000)
kal_public <- NormalizeData(kal_public, normalization.method = "LogNormalize", scale.factor = 100000)
kal_merged <- NormalizeData(kal_merged, normalization.method = "LogNormalize", scale.factor = 100000)
gc()

#Variable features
cell_pbmc <- FindVariableFeatures(cell_pbmc, selection.method = "vst", nfeatures = 2000)
kal_inhouse <- FindVariableFeatures(kal_inhouse, selection.method = "vst", nfeatures = 2000)
kal_public <- FindVariableFeatures(kal_public, selection.method = "vst", nfeatures = 2000)
kal_merged <- FindVariableFeatures(kal_merged, selection.method = "vst", nfeatures = 2000)


# Identify the 10 most highly variable genes
top10_cell <- head(VariableFeatures(cell_pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(cell_pbmc)
plot1 <- LabelPoints(plot = plot1, points = top10_cell, repel = TRUE) + ggtitle("cellranger")
plot1
#Kallisto variable features
top10_kal <- head(VariableFeatures(kal_inhouse), 10)

plot1 <- VariableFeaturePlot(kal_inhouse)
plot1 <- LabelPoints(plot = plot1, points = top10_kal, repel = TRUE) + ggtitle("KalBus")
plot1

top10_kal <- head(VariableFeatures(kal_public), 10)

plot1 <- VariableFeaturePlot(kal_public)
plot1 <- LabelPoints(plot = plot1, points = top10_kal, repel = TRUE) + ggtitle("KalBus")
plot1

remove(plot1)

#data scaling
#Next, we apply a linear transformation (‘scaling’) 
#that is a standard pre-processing step prior to dimensional reduction techniques like PCA. The ScaleData() function:
gc()
#Cellranger scaling
cell_pbmc.genes <- rownames(cell_pbmc)
cell_pbmc <- ScaleData(cell_pbmc, features = cell_pbmc.genes)

#Kallisto inhouse scaling
kal_inhouse.genes <- rownames(kal_inhouse)
kal_inhouse <- ScaleData(kal_inhouse, features = kal_inhouse.genes)

#Kallisto public scaling
kal_public.genes <- rownames(kal_public)
kal_public <- ScaleData(kal_public, features = kal_public.genes)

#Kallisto merged scaling
kal_merged.genes <- rownames(kal_merged)
kal_merged <- ScaleData(kal_merged, features = kal_merged.genes)

#Cell cycle scores
gc()

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

kal_inhouse <- CellCycleScoring(kal_inhouse, s.features = s.genes, g2m.features = g2m.genes, set.indent=TRUE)
kal_public <- CellCycleScoring(kal_public, s.features = s.genes, g2m.features = g2m.genes, set.indent=TRUE)
kal_merged <- CellCycleScoring(kal_merged, s.features = s.genes, g2m.features = g2m.genes, set.indent=TRUE)
gc()

#PCA run
cell_pbmc <- RunPCA(cell_pbmc, features = VariableFeatures(object = cell_pbmc))
kal_inhouse <- RunPCA(kal_inhouse, features = VariableFeatures(object = kal_inhouse))
kal_public <- RunPCA(kal_public, features = VariableFeatures(object = kal_public))
kal_merged <- RunPCA(kal_merged, features = VariableFeatures(object = kal_merged))


#Examination of the PCA results
print(cell_pbmc[["pca"]], dims = 1:5, nfeatures = 5)
print(kal_inhouse[["pca"]], dims = 1:5, nfeatures = 5)


#ElbowPlot
#Cellranger
ElbowPlot(cell_pbmc) + ggtitle("cellranger")
#Kallisto inhouse
ElbowPlot(kal_inhouse) + ggtitle("KalBus inhouse")
#Kallisto public
ElbowPlot(kal_public) + ggtitle("KalBus public")

gc()

amountOfDims <- 15
#Going further with 15 PC in the downstream analysis
#Clustering of the cells
#Cellranger
cell_pbmc <- FindNeighbors(cell_pbmc, dims = 1:amountOfDims)
cell_pbmc <- FindClusters(cell_pbmc, resolution = 0.3)
head(Idents(cell_pbmc), 5)
#Kallisto inhouse
kal_inhouse <- FindNeighbors(kal_inhouse, dims = 1:amountOfDims)
kal_inhouse <- FindClusters(kal_inhouse, resolution = 0.3)
head(Idents(kal_inhouse), 5)
#Kallisto public
kal_public <- FindNeighbors(kal_public, dims = 1:amountOfDims)
kal_public <- FindClusters(kal_public, resolution = 0.3)
head(Idents(kal_public), 5)
#Kallisto merged
kal_merged <- FindNeighbors(kal_merged, dims = 1:amountOfDims)
kal_merged <- FindClusters(kal_merged, resolution = 0.5)
head(Idents(kal_merged), 5)


#UMAP visualisation
#Cellranger
cell_pbmc <- RunUMAP(cell_pbmc, dims = 1:amountOfDims)
DimPlot(cell_pbmc, reduction = "umap") + ggtitle("cellranger")
#Kallisto inhouse
kal_inhouse <- RunUMAP(kal_inhouse, dims = 1:amountOfDims)
Idents(kal_inhouse) <- "seurat_clusters"
DimPlot(kal_inhouse, reduction = "umap") + ggtitle("KalBus")

Idents(kal_inhouse) <- "orig.ident"
DimPlot(kal_inhouse, reduction = "umap")

Idents(kal_inhouse) <- "sample_name"
DimPlot(kal_inhouse, reduction = "umap")

#Kallisto public
kal_public <- RunUMAP(kal_public, dims = 1:amountOfDims)
Idents(kal_public) <- "seurat_clusters"
DimPlot(kal_public, reduction = "umap")

Idents(kal_public) <- "sample_name"
DimPlot(kal_public, reduction = "umap")

Idents(kal_public) <- "replicate"
DimPlot(kal_public, reduction = "umap")

Idents(kal_public) <- "timepoint"
DimPlot(kal_public, reduction = "umap")

#Kallisto Merged
kal_merged <- RunUMAP(kal_merged, dims = 1:amountOfDims)
Idents(kal_merged) <- "seurat_clusters"
DimPlot(kal_merged, reduction = "umap")

Idents(kal_merged) <- "sample_name"
DimPlot(kal_merged, reduction = "umap")

Idents(kal_merged) <- "replicate"
DimPlot(kal_merged, reduction = "umap")

Idents(kal_merged) <- "timepoint"
DimPlot(kal_merged, reduction = "umap")

gc()
kal_merged


#saveRDS(kal_merged, "/exports/sascstudent/thomas/R_output/hiPSC_kallisto_merged_incomplete.rds")
#kal_merged <- readRDS("/exports/sascstudent/thomas/R_output/hiPSC_kallisto_merged_incomplete.rds")
kal_merged


#####################################################################
#Kallisto inhouse batch correction
kal_inhouse <- RunFastMNN(object.list = SplitObject(kal_inhouse, split.by = "sample_name"))

kal_inhouse <- FindNeighbors(kal_inhouse, c(1:amountOfDims), reduction = "mnn")
kal_inhouse <- FindClusters(kal_inhouse, resolution = 0.3)

kal_inhouse <- RunUMAP(kal_inhouse, reduction = "mnn", dims = c(1:amountOfDims))

DimPlot(kal_inhouse, reduction = "umap", group.by = "seurat_clusters")
DimPlot(kal_inhouse, reduction = "umap", group.by = "sample_name")
DimPlot(kal_inhouse, reduction = "umap", group.by = "orig.ident")

#saveRDS(kal_inhouse, "/exports/sascstudent/thomas/R_output/hiPSC_kallisto_inhouse_mnn.rds")
#####################################################################
#Kallisto public batch correction
gc()
kal_public <- RunFastMNN(object.list = SplitObject(kal_public, split.by = "replicate"))

kal_public <- FindNeighbors(kal_public, c(1:amountOfDims), reduction = "mnn")
kal_public <- FindClusters(kal_public, resolution = 0.3)

kal_public <- RunUMAP(kal_public, reduction = "mnn", dims = c(1:amountOfDims))
Idents(kal_public) <- "seurat_clusters"
DimPlot(kal_public, reduction = "umap")

Idents(kal_public) <- "sample_name"
DimPlot(kal_public, reduction = "umap")

Idents(kal_public) <- "replicate"
DimPlot(kal_public, reduction = "umap")

Idents(kal_public) <- "timepoint"
DimPlot(kal_public, reduction = "umap")


#saveRDS(object = kal_public, file="/exports/sascstudent/thomas/R_output/hiPSC_kallisto_public_mnn.rds")
#######################################################################
#########################################################################

inhouse_clusters <- kal_inhouse[["seurat_clusters"]] %>%rownames_to_column()
inhouse_clusters["rowname"] <- paste0("hiPSC_", inhouse_clusters$rowname)
inhouse_clusters <- inhouse_clusters %>% column_to_rownames()
kal_merged[["hiPSC_only_clustering"]] <- inhouse_clusters
Idents(kal_merged) <- "orig.ident"
kal_merged <- RunFastMNN(object.list = SplitObject(kal_merged, split.by = "replicate"))
gc()

kal_merged <- FindNeighbors(kal_merged, c(1:15), reduction = "mnn")
kal_merged <- FindClusters(kal_merged, resolution = 0.35)
kal_merged <- RunUMAP(kal_merged, reduction = "mnn", dims = c(1:15))

DimPlot(kal_merged, reduction = "umap", group.by = "seurat_clusters")
DimPlot(kal_merged, reduction = "umap", group.by = "sample_id")
DimPlot(kal_merged, reduction = "umap", group.by = "replicate")
DimPlot(kal_merged, reduction = "umap", group.by = "timepoint")
DimPlot(kal_merged, reduction = "umap", group.by = "hiPSC_only_clustering")

DimPlot(cell_merged, reduction = "umap", group.by = "seurat_clusters")
DimPlot(cell_merged, reduction = "umap", group.by = "sample_id")
DimPlot(cell_merged, reduction = "umap", group.by = "replicate")
DimPlot(cell_merged, reduction = "umap", group.by = "timepoint")
DimPlot(cell_merged, reduction = "umap", group.by = "hiPSC_only_clustering")



saveRDS(object = kal_merged, file="/exports/sascstudent/thomas/R_output/hiPSC_kallisto_merged_mnn.rds")
########################################################################


##################################################################

#remove(H0_sample1, H0_sample2, H48_sample, H120_sample)
#saveRDS(object = kal_pbmc, file = "/exports/sascstudent/thomas/R_output/hiPSC_complete_mnn.rds")
#cell_pbmc <- readRDS("/exports/sascstudent/thomas/hiPSC_susana/hiPSC_complete_mnn.rds")

kal_inhouse <- readRDS("/exports/sascstudent/thomas/R_output/hiPSC_kallisto_inhouse_mnn.rds")
#kal_public <- readRDS("/exports/sascstudent/thomas/R_output/hiPSC_kallisto_public_mnn.rds")
kal_merged <- readRDS("/exports/sascstudent/thomas/R_output/hiPSC_kallisto_merged_mnn.rds")

cell_inhouse <- readRDS("/exports/sascstudent/thomas/hiPSC_susana/hiPSC_complete_mnn.rds")
cell_merged <- readRDS("/exports/sascstudent/thomas/chen_hiPSC/UCLA2_hiPSC_mnn.rds")

Project(kal_inhouse) <- "kal_inhouse"
Project(kal_merged) <- "kal_merged"
Project(cell_inhouse) <- "cell_inhouse"
Project(cell_merged) <- "cell_merged"

DimPlot(kal_inhouse, reduction = "umap", group.by = "seurat_clusters")
DimPlot(cell_inhouse, reduction = "umap", group.by = "seurat_clusters")


kal_merged
cell_merged

Idents(kal_merged) <- "seurat_clusters"
DimPlot(kal_merged , reduction = "umap")

Idents(cell_merged) <- "seurat_clusters"
DimPlot(cell_merged , reduction = "umap")


#Add any extra meta features, such as annotations. Generate the h5ad file from seurat objects

cellranger_cluster_ann <- cell_inhouse[["seurat_clusters"]]
rownames(cellranger_cluster_ann) <- rownames(cellranger_cluster_ann) %>% str_extract(. , pattern = ".+[ATCG]+")
head(rownames(cellranger_cluster_ann))

cellranger_cluster_ann_df <- cellranger_cluster_ann %>% rownames_to_column()
factor_columns <- sapply(cellranger_cluster_ann_df, is.factor)
cellranger_cluster_ann_df[factor_columns] <- lapply(cellranger_cluster_ann_df[factor_columns], as.character)
cellranger_cluster_ann_df <- cellranger_cluster_ann_df %>% column_to_rownames()
kal_inhouse[["cellranger_cluster_ann"]] <- cellranger_cluster_ann_df

remove(factor_columns, cellranger_cluster_ann, cellranger_cluster_ann_df)

colnames(kal_inhouse[[]])

kal_inhouse[["kallisto_cluster_ann"]] <- clust_char(kal_inhouse)
SaveH5Seurat(kal_inhouse, filename = "/exports/sascstudent/thomas/R_output/kal_inhouse.h5seurat", overwrite = T)
Convert("/exports/sascstudent/thomas/R_output/kal_inhouse.h5seurat", dest = "h5ad", overwrite = T)

#Kal merged####################################

head(rownames(kal_merged[[]]), 10)
head(rownames(cell_merged[[]]), 10)
head(rownames(kal_inhouse[[]]), 10)
head(rownames(cell_inhouse[[]]), 10)



rownames(cell_merged[[]]) %>% str_sub(end = -3)
cell_merged.clusters <- cell_merged[["seurat_clusters"]]
rownames(cell_merged.clusters) <- rownames(cell_merged.clusters) %>% str_sub(end = -3)

kal_merged[["cellranger_merged_clustering"]] <- cell_merged.clusters

cell_inhouse.clusters <- cell_merged[["hiPSC_only_clustering"]]
rownames(cell_inhouse.clusters) <- rownames(cell_inhouse.clusters) %>% str_sub(end = -3)

kal_merged[["cellranger_inhouse_clustering"]] <- cell_inhouse.clusters

DimPlot(kal_merged, group.by = "seurat_clusters")
DimPlot(kal_merged, group.by = "hiPSC_only_clustering")
DimPlot(kal_merged, group.by = "cellranger_inhouse_clustering")
DimPlot(kal_merged, group.by = "cellranger_merged_clustering")

colnames(kal_merged[[]])

kal_merged[["kallisto_merged_clusters_ch"]] <- clust_char(kal_merged, "seurat_clusters")
kal_merged[["kallisto_inhouse_clusers_ch"]] <- clust_char(kal_merged, "hiPSC_only_clustering")
kal_merged[["cellranger_merged_clusters_ch"]] <- clust_char(kal_merged, "cellranger_merged_clustering")
kal_merged[["cellranger_inhouse_clusters_ch"]] <- clust_char(kal_merged, "cellranger_inhouse_clustering")

SaveH5Seurat(kal_merged, filename = "/exports/sascstudent/thomas/R_output/kal_merged.h5seurat", overwrite = T)
Convert("/exports/sascstudent/thomas/R_output/kal_merged.h5seurat", dest = "h5ad", overwrite = T)



############################################################################

#Marker genes of Cellranger CL0 and CL1
Idents(cell_inhouse) <- "seurat_clusters"
cell_cl0_pos <- FindMarkers(cell_inhouse, logfc.threshold = 0.25, min.pct = 0.25, only.pos = T, 
            ident.1 = "0", ident.2 = "1") %>% filter(pct.1 > 0.6, p_val_adj < 0.05)
cell_cl1_pos <- FindMarkers(cell_inhouse, logfc.threshold = 0.25, min.pct = 0.25, only.pos = T, 
                            ident.1 = "1", ident.2 = "0") %>% filter(pct.1 > 0.6, p_val_adj < 0.05)

rownames(cell_cl0_pos) %>% cat(sep = ", ")
rownames(cell_cl1_pos) %>% cat(sep = ", ")
c(rownames(cell_cl0_pos),rownames(cell_cl1_pos)) %>% cat(sep = " ")


#Marker genes of Kallisto CL0 and CL1
Idents(kal_inhouse) <- "seurat_clusters"
kal_cl0_pos <- FindMarkers(kal_inhouse, logfc.threshold = 0.25, min.pct = 0.25, only.pos = T, 
                            ident.1 = "0", ident.2 = "1") %>% filter(pct.1 > 0.6, p_val_adj < 0.05)
kal_cl1_pos <- FindMarkers(kal_inhouse, logfc.threshold = 0.25, min.pct = 0.25, only.pos = T, 
                            ident.1 = "1", ident.2 = "0") %>% filter(pct.1 > 0.6, p_val_adj < 0.05)

kal_cl0_pos %>% filter(pct.2 < 0.5) %>% rownames() %>% cat(sep = ", ")
kal_cl1_pos %>% filter(pct.2 < 0.5) %>% rownames() %>% cat(sep = ", ")

c(rownames(kal_cl0_pos %>% filter(pct.2 < 0.5)), rownames(kal_cl1_pos %>% filter(pct.2 < 0.5))) %>% cat(sep = " ")

####################################
cell_cl0_pos %>% rownames() %>% cat(sep = "\n")
cell_cl1_pos %>% rownames() %>% cat(sep = ",")
###############################################
kal_cl0_pos %>% rownames() %>% cat(sep = ",")
kal_cl1_pos %>% rownames() %>% cat(sep = "\n")
#################################################





#Gprofile Cell CL0+CL1 markers
cell_cl0_pos.gostres <- gost(cell_cl0_pos %>% rownames(), organism = "hsapiens")
cell_cl1_pos.gostres <- gost(cell_cl1_pos %>% rownames(), organism = "hsapiens")
gostplot(cell_cl0_pos.gostres)
gostplot(cell_cl1_pos.gostres)
gost(cell_cl0_pos %>% rownames(), organism = "hsapiens", as_short_link = T)
gost(cell_cl1_pos %>% rownames(), organism = "hsapiens", as_short_link = T)
#################################################################
kal_cl0_pos.gostres <- gost(kal_cl0_pos %>% rownames(), organism = "hsapiens")
kal_cl1_pos.gostres <- gost(kal_cl1_pos %>% rownames(), organism = "hsapiens")
gostplot(kal_cl0_pos.gostres)
gostplot(kal_cl1_pos.gostres)
gost(kal_cl0_pos %>% rownames(), organism = "hsapiens", as_short_link = T)
gost(kal_cl1_pos %>% rownames(), organism = "hsapiens", as_short_link = T)








kal_markers <- FindAllMarkers(kal_inhouse, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
test <- kal_markers %>%
  group_by(cluster) %>%
  slice_max(n = 4, order_by = avg_log2FC)

kal_markers <- FindMarkers(kal_inhouse, only.pos = T, min.pct = 0.25, 
                           ident.1 = "0", ident.2 = "1", min.diff.pct = 0.25)

kal_markers_cl0 <- FindMarkers(kal_inhouse, ident.1 = "0", ident.2 = "1", min.pct = 0.25, only.pos = T)
kal_markers_cl1 <- FindMarkers(kal_inhouse, ident.1 = "1", ident.2 = "0", min.pct = 0.25, only.pos = T)

cell_markers_cl0 <- FindMarkers(cell_inhouse, ident.1 = "0", ident.2 = "1", min.pct = 0.25, only.pos = T)
cell_markers_cl1 <- FindMarkers(cell_inhouse, ident.1 = "1", ident.2 = "0", min.pct = 0.25, only.pos = T)

kal_markers_cl0 <- kal_markers_cl0 %>% filter(pct.1>0.6 & p_val_adj <0.05 )
kal_markers_cl1 <- kal_markers_cl1 %>% filter(pct.1>0.6 & p_val_adj <0.05 )

cell_markers_cl0 <- cell_markers_cl0 %>% filter(pct.1>0.6 & p_val_adj <0.05 )
cell_markers_cl1 <- cell_markers_cl1 %>% filter(pct.1>0.6 & p_val_adj <0.05 )

cell_markers_cl0
cell_markers_cl1

kal_markers_cl0 %>% top_n(10, avg_log2FC)
kal_markers_cl1 %>% top_n(10, avg_log2FC)

intersect(rownames(cell_markers_cl0), rownames(kal_markers_cl1))
intersect(rownames(cell_markers_cl1), rownames(kal_markers_cl0))

overlap_feat <- intersect(rownames(kal_markers), rownames(cell_markers))


kal_markers[["pct_1_2.diff"]] <- kal_markers[["pct.1"]] - kal_markers[["pct.2"]]
cell_markers[["pct_1_2.diff"]] <- cell_markers[["pct.1"]] - cell_markers[["pct.2"]]

kal_markers %>% filter(rownames(.) %in% overlap_feat) %>% arrange(desc(pct_1_2.diff))
cell_markers %>% filter(rownames(.) %in% overlap_feat) %>% arrange(desc(pct_1_2.diff))

overlap_feat

write.table(overlap_feat, row.names = F, quote = F, sep = ",", file = "/exports/sascstudent/thomas/R_output/overlap_feat_cl0_cl1.csv")


kal_markers_cl0 <- FindMarkers(kal_inhouse, ident.1 = "0", ident.2 = NULL, logfc.threshold = 0.25, min.pct = 0.25)
kal_markers_cl1 <- FindMarkers(kal_inhouse, ident.1 = "1", ident.2 = NULL, logfc.threshold = 0.25, min.pct = 0.25)
kal_markers_cl0 %>% top_n(8, avg_log2FC)
kal_markers_cl1 %>% top_n(8, avg_log2FC)

cell_markers_cl0 <- FindMarkers(cell_inhouse, ident.1 = "0", ident.2 = NULL, logfc.threshold = 0.25, min.pct = 0.25)
cell_markers_cl1 <- FindMarkers(cell_inhouse, ident.1 = "1", ident.2 = NULL, logfc.threshold = 0.25, min.pct = 0.25)
cell_markers_cl0 %>% top_n(8, avg_log2FC)
cell_markers_cl1 %>% top_n(8, avg_log2FC)


kal_markers <- FindAllMarkers(kal_inhouse, logfc.threshold = 0.25, min.pct = 0.25)

cell_markers <- FindAllMarkers(cell_inhouse, logfc.threshold = 0.25, min.pct = 0.25)





cell_markers <- FindAllMarkers(cell_inhouse, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
Idents(cell_inhouse) <- "seurat_clusters"
kal_filt_markers <- kal_markers %>% filter(pct.1 > 0.6 & p_val_adj < 0.05)

kal_top_markers <- kal_markers %>%
  group_by(cluster) %>%
  top_n(30, avg_log2FC)


write.table(kal_top_markers, row.names = F, quote = F, sep = "\t",
            file = "/exports/sascstudent/thomas/R_output/kal_top_markers.tsv")





cell_markers <- FindAllMarkers(cell_inhouse, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
cell_markers %>%
  group_by(cluster) %>%
  slice_max(n = 4, order_by = avg_log2FC)

cell_filt_markers <- cell_markers %>% filter(pct.1 > 0.6 & p_val_adj < 0.05)

cell_top_markers <- cell_markers %>%
  group_by(cluster) %>%
  top_n(30, avg_log2FC)

write.table(cell_top_markers, row.names = F, quote = F, sep = "\t",
            file = "/exports/sascstudent/thomas/R_output/cell_top_markers.tsv")



interest_genes <- read_tsv(file =  "/exports/sascstudent/thomas/R_output/kal_merged-gene-sets-test.tsv", 
         skip = 3, col_names = c("dataset", "gene"))


cluster1_high <- interest_genes %>%
  filter(dataset == "Cluster 1 high genes") %>%
  select(gene) %>% .$gene

cluster2_high <- interest_genes %>%
  filter(dataset == "Cluster 2 high") %>%
  select(gene) %>% .$gene

cluster1_high <- c("HIST1H1D","HIST1H1B","HIST1H1E")
cluster2_high <- c("","","")

#Cluster 1 high markers vlnplot
VlnPlot(cell_inhouse, features = cluster1_high, ncol = 1) |
VlnPlot(kal_inhouse, features = cluster1_high, ncol = 1)

#Cluster 1 high markers vlnplot
VlnPlot(cell_inhouse, features = "PLK1", ncol = 1) |
VlnPlot(kal_inhouse, features = "PLK1", ncol = 1)



cell_cl0_markers <- c("SOX2", "ZIC2", "USP44", "POLR3G")
cell_cl1_markers <- c("HIST1H1B", "HIST1H1E", "USP44", "HIST1H1D")

kal_cl0_markers <- c("SFRP1", "RAB17", "USP44", "LINC02700")
kal_cl1_markers <- c("NEFL", "UTF1", "ONECUT1", "NODAL")


#Cluster 0 markers from cellranger####################################################
print(cell_cl0_markers)
cell_markers %>%
  filter(rownames(.) %in% cell_cl0_markers)
kal_markers %>%
  filter(rownames(.) %in% cell_cl0_markers)
#Cluster 0 markers from Kallisto####################################################
print(kal_cl0_markers)
cell_markers %>%
  filter(rownames(.) %in% kal_cl0_markers)
kal_markers %>%
  filter(rownames(.) %in% kal_cl0_markers)

#Cell cluster 0 markers vlnplot
VlnPlot(cell_inhouse, features = cell_cl0_markers, ncol = 1) |
VlnPlot(kal_inhouse, features = cell_cl0_markers, ncol = 1)
#kal cluster 0 markers vlnplot
VlnPlot(cell_inhouse, features = kal_cl0_markers, ncol = 1) |
VlnPlot(kal_inhouse, features = kal_cl0_markers, ncol = 1)
#Cell cluster 1 markers vlnplot
VlnPlot(cell_inhouse, features = cell_cl1_markers, ncol = 1, combine = T) |
VlnPlot(kal_inhouse, features = cell_cl1_markers, ncol = 1, combine = T)
#kal cluster 1 markers vlnplot
VlnPlot(cell_inhouse, features = kal_cl1_markers, ncol = 1) |
VlnPlot(kal_inhouse, features = kal_cl1_markers, ncol = 1)

DimPlot(kal_inhouse, reduction = "umap")

FeaturePlot(kal_inhouse, features = c("POU5F1"))
FeaturePlot(kal_inhouse, features = c("NANOG"))
FeaturePlot(kal_inhouse, features = c("NANOS3"))
FeaturePlot(kal_inhouse, features = c("PRDM1"))
FeaturePlot(kal_inhouse, features = c("SOX17"))
FeaturePlot(kal_inhouse, features = c("ISL1"))
FeaturePlot(kal_inhouse, features = c("TFAP2A"))
FeaturePlot(kal_inhouse, features = c("GATA6"))
FeaturePlot(kal_inhouse, features = c("PDGFRA"))
FeaturePlot(kal_inhouse, features = c("FOXF1"))
#all identical to the ones in the paper

#Merged Dataset feature plots
FeaturePlot(kal_merged, features = c("NANOG"))
FeaturePlot(kal_merged, features = c("TFAP2C"))
FeaturePlot(kal_merged, features = c("ISL1"))
FeaturePlot(kal_merged, features = c("GATA6"))



query_list <- list()
clusters <- unique(markers$cluster)
for (cl in clusters) {
  cluster <- paste0("cl_", cl)
  query_list[[cluster]] <- markers %>%
    filter(cluster == cl) %>%
    arrange(p_val_adj) %>%
    dplyr::select(gene)
}

#Loading the RDS object so i dont have to repeat earlier steps #################
#cell_pbmc <- readRDS("cell_pbmc3k_final.rds")
#kal_pbmc <- readRDS("kal_pbmc3k_final.rds")

#Rand index to compare the two clustering globally #############################
cell.clusters <- cell_pbmc[[]] %>%
  select(seurat_clusters)

kal.clusters <- kal_inhouse[[]] %>%
  select(seurat_clusters)

com.cluster.barcodes <- sort(intersect(rownames(cell.clusters), rownames(kal.clusters)))

cell_cluster <- as.integer(cell.clusters[com.cluster.barcodes,"seurat_clusters"])
kal_cluster <- as.integer(kal.clusters[com.cluster.barcodes,"seurat_clusters"])

rand.index(cell_cluster, kal_cluster)
adj.rand.index(cell_cluster, kal_cluster)

remove(cell.clusters, kal.clusters, cell_cluster, kal_cluster, com.cluster.barcodes)


#Fix for cellranger suffix
get_cluster_count <- function(cell.cluster.num, project1, project2) {
  cell.cluster.barcodes <- project1[[]] %>%
    filter(seurat_clusters == cell.cluster.num) %>%
    rownames() %>%
    str_extract(. , pattern = ".+[ATCG]+")
  project1.cluster.name <- paste0(Project(project1),".clust_",cell.cluster.num)
  test <- project2[[]]%>%
    select(seurat_clusters) %>%
    rownames_to_column() %>%
    filter(rowname %in% cell.cluster.barcodes) %>%
    column_to_rownames() %>%
    group_by(seurat_clusters) %>%
    summarise(project1.cluster.name = length(seurat_clusters)) %>%
    column_to_rownames("seurat_clusters")
  rownames(test) <- lapply(rownames(test), function(x) paste0(Project(project2), ".clust_", x))
  colnames(test) <- paste0(Project(project1),".clust_",cell.cluster.num)
  test <- test %>% rownames_to_column()
  return(test)
}

get_shared_cells <- function(project1, project2){
  clus_list <- lapply(levels(project1@meta.data$seurat_clusters), FUN = function(x) get_cluster_count(x, project1, project2))
  print(length(clus_list))
  print(levels(project1@meta.data$seurat_clusters))
  clust_share <- data.frame(x=0:length(clus_list))
  rownames(clust_share) <- lapply(seq(1:(length(clus_list)+1))-1, function(x) paste0(Project(project2), ".clust_", x))
  clust_share <- clust_share %>% rownames_to_column()
  clust_share <- subset(clust_share, select = -c(x))
  
  for (i in seq(1:length(clus_list))){
    clust_share <- left_join(clust_share, clus_list[[i]], by="rowname")
  }
  clust_share <- clust_share %>%
    column_to_rownames() %>%
    mutate_all(~replace(., is.na(.), 0))
  for (i in seq(1:ncol(clust_share))){
    names(clust_share)[names(clust_share) == colnames(clust_share)[i]] <-paste0(colnames(clust_share)[i], ".", as.character(sum(clust_share[i])))
  }
  for (i in seq(1:nrow(clust_share))){
    rownames(clust_share)[rownames(clust_share) == rownames(clust_share)[i]] <- paste0(rownames(clust_share)[i], ".", sum(clust_share[i,]))
  }
  remove(i, clus_list)
  return(clust_share)
}


Project(kal_merged) <- "kal.merged"
Project(cell_merged) <- "cell.merged"


clust_share <- get_shared_cells(cell_merged, kal_merged)
clust_share <- clust_share[1:length(rownames(clust_share))-1,]


################################################################################
#Clusters similarity matrix percentage
{
  clust_share.perc <- data.frame(clust_share)
  for (i in seq(1:length(colnames(clust_share)))) {
    newcol <- clust_share[,i] / sum(clust_share[,i])
    clust_share.perc[,i] <- round(newcol * 100, 2)
  }
  remove(i, newcol)
}
#Clusters similarity heatmap
{
  sample1.clusters <- colnames(clust_share)
  sample2.clusters <- rownames(clust_share)
  data <- expand_grid(sample1.clusters, sample2.clusters)
  for (i in seq(1:nrow(data))){
    data[i, "cells"] <- clust_share.perc[as.character(data[i,"sample2.clusters"]), as.character(data[i,"sample1.clusters"])]
  }
  remove(sample1.clusters,sample2.clusters,i)
}

data %>%
  arrange(cells) %>%
  mutate(sample1.clusters=factor(sample1.clusters, levels = unique(sample1.clusters))) %>%
  mutate(sample2.clusters=factor(sample2.clusters, levels = unique(sample2.clusters))) %>%
  ggplot(aes(sample1.clusters, sample2.clusters, fill = cells)) + 
    geom_tile() + 
    geom_text(aes(label = cells), color = "#FFFFFF") +
    theme(axis.text.x = element_text(angle=70, hjust = 1)) + 
    scale_fill_gradient(breaks=c(100,75,50,25,0), labels=c("100%", "75%", "50%", "25%","0%"))

###############################################################


